### ISSUE TITLE
portable variant

### ISSUE THREAD

**Issue by willscott** [oasisprotocol/deoxysii-rust#12]
we should have a variant of this library that can be compiled to wasm, which probably means not using the use `core::arch::x86_64::...` or the assembly.

**Comment by Yawning** [comment]
The time consuming and annoying part of this is having to implement a constant time AES round function.  I guess the path of least resistance would be to use one based on the BearSSL code, it's what the Go and JS implementations do.

Though, part of me thinks that doing just the round function and format conversion stuff in wasm should be enough, and it would be less frustrating for me to use wasm s-expressions than rust.

**Comment by KirilMihaylov** [comment]
Perhaps, [RustCrypto's soft AES](https://github.com/RustCrypto/block-ciphers/tree/master/aes) implementation could be used or ported to fit Deoxys's specification.
Note, that it did receive a third-party review, so changing just some constants, if that's the case, should be sufficient to have a verified implementation.

**Comment by Yawning** [comment]
> Perhaps, [RustCrypto's soft AES](https://github.com/RustCrypto/block-ciphers/tree/master/aes) implementation could be used or ported to fit Deoxys's specification. Note, that it did receive a third-party review, so changing just some constants, if that's the case, should be sufficient to have a verified implementation.

That might work, though there isn't anything wrong with the BearSSL code either.  For what it's worth I am against doing this for the reasoning in the original issue, because WASM as specified is an unsafe environment for cryptography.

RustCrypto also provides the Deoxys family now, although I have not looked at their portable implementation in depth (the hardware accelerated flavor was terrible when I checked back in Febuary 2022, because it is 25x slower).

**Comment by Yawning** [comment]
I basically never want a version of this that can be compiled to WASM, so I'm closing this as a WONTFIX.
